### ISSUE TITLE
Plugin does not work with node v5 or v6 LTS installed

### ISSUE THREAD

**Issue by eonarheim** [iradul/vscode-phantomjs-debug#10]
I recently ran into a situation where this plugin was working on one of my dev machines but not the other. 

The symptom that manifested was after hitting the debug "play" button it would just exit out and not start the debugging session and hit breakpoints (I used the simple example in the documentation to test this). The windows task manager would show an orphaned phantomjs.exe running, and subsequent attempts would spawn more processes.

I went down the rabbit hole trying to figure out why my debug setup was not working and discovered that one machine had node v5 installed, since this is not the LTS release I then updated to v6 LTS to attempt to fix the problem. The v6 LTS version still did not work.

The eventual fix was reverting my install to match the node on the working machine, which was the v4 LTS. Specifically I reverted to node v4.2.6 to get this plugin working. My guess is that node has perhaps changed how their process spawning api works causing the breakage.

Let me know if you want any more info on this issue.
Erik

**Comment by iradul** [comment]
It shouldn't be related to your installed `nodejs` version since `vsc` and its extensions are running inside `vsc` own `nodejs` which is part of [Electron](https://github.com/electron/electron).

By default PhantomJS debugger is using port `9222` for debugging. You need to make sure that nothing else is using this port when you start the PJS debugger. Also kill all orphan phantomjs processes before you run debugger since one of those could hold up this port.
Alternatively you can set some other port in `launch.json` with `"port": 4321`.

If you're still having troubles add this `"verboseDiagnosticLogging": true` to your `launch.json` config and send me the output.

**Comment by iradul** [comment]
Closing since I got no reply from you
