### ISSUE TITLE
Can't start debugging on code 1.10.2

### ISSUE THREAD

**Issue by shangerxin** [iradul/vscode-phantomjs-debug#13]
## Reproduce steps:

1. Install debugger for phantomjs extension in code. 
2. Reload/restart code
3. Add launch.json with content:
	"configurations": [{
		"name": "Launch",
		"type": "phantomjs",
		"request": "launch",
		"file": "${workspaceRoot}/headless.js",
		"webRoot": "${workspaceRoot}",
		"runtimeExecutable": "${workspaceRoot}/phantomjs.exe",
		"runtimeArgs": [],
		"scriptArgs": [],
		"sourceMaps": true
	}]

4. Start debugging with F5 and get error message
Cannot connect to runtime process, timeout after 10000 ms - (reason: 404 - Not Found. The requested location ...

## Environment:

OS: window 10 64bit en 
Code: 1.10.2 en
phantomjs: 2.1.1
Other extensions in Code:
Beautify 1.0.2
C/C++ 0.10.5 
C/C++ Clang Command Adapter 
C# 1.8.0
Clang-Format
ClangComplete
Code Runner 0.6.14 
Debugger for Chrome
Erlang/OTP
Go 
JavaScript (ES6) code snippets 
MagicPython
Mocha 
MochaSnippets 
npm 
Python
Toggle Header/Source 
Unit Test Navigate 
vscode-icons 
XML Tools

## Note:

- Also tried reference phantomjs.exe from other directory, not work
- The phantomjs option does not appear when click Add Configuration in Code. The content of launch.json is copied from the extension detail of Debugger for PhantomJS
- Manually run debugging command as administrator and can't access the remote debugging page with Chrome from localhost:9000 or 127.0.0.1:9000. Not sure it's relative or not
> phantomjs.exe --remote-debugger-port=9000 script-path

**Comment by iradul** [comment]
> Manually run debugging command as administrator and can't access the remote debugging page with Chrome from localhost:9000 or 127.0.0.1:9000. Not sure it's relative or not
>> phantomjs.exe --remote-debugger-port=9000 script-path

This is actually relevant info because PhantomJS Code debugger is totally relying on `--remote-debugger-port` option. Only difference is that it uses port `9222`. If you cannot debug with Google Chrome after running `phantomjs --remote-debugger-port=9222 your_script` then Code debugger won't work neither.
It seems to me that you might have some firewall that is blocking remote debugging. Try disabling any firewall you have.
Also you might first want to try debugging some simple script just to make sure that script itself is not the problem, for instance try to debug this script:
```js
console.log("Test!");
debugger;
phantom.exit();

```
Anyway, I just tested debugger on a Windows 10 box with Code 1.10.2 and PhantomJS 2.1.1 and it worked.

**Comment by shangerxin** [comment]
Thank you for the helping. 

It seems that is relative to my proxy settings. Although i have set bypass local address but still not works. If the proxy is disabled then everything works fine.

**Comment by iradul** [comment]
Cool, glad that it worked for you.
